#MySql config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/new_schema?serverTimezone=UTC&characterEncoding=UTF-8
    username: test_user
    password: admin

  #JPA config
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

#Thymleaf prefix, suffix
  #정적 리소스 변화있을시 바로 반영
  devtools:
    restart:
      enabled: true

  #Thymleaf 참조경로
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    #Thymleaf에 대한 캐시를 남기지 않는다 cache=false 설정 (운영시 true)
    cache: false
    #templates 디렉토리에 파일이 있는지 없는지 체크, 없으면 에러를 발생
    check-template-location: true


